### ISSUE TITLE
Some questions about your paper and code

### ISSUE THREAD

**Issue by junleiz** [alecwangcq/GraSP#1]
Hello, Thank you very much for your code. I am a lit bit confused about some details in your paper. Could you please help me with them?

1. 
![image](https://user-images.githubusercontent.com/26025961/75116854-63ac8800-56a7-11ea-8265-57663f23ab8f.png)
In your equation 8, you multiple the Hg with -theta. I do not understand why you have to multiply Hg with -theta since Hg is already a measurement of the importance.

2. In your code, you use 1000 examples for cifar100 and divide them into 4*250. While you computing the Hessian vector product: z += (grad_w[count].data * grad_f[count]).sum(), you use different numbers of data for grad_w and grad_f. The grad_w is the sum of gradients for 4*250, but grad_f is only the gradients of this batch of 250 examples. Why do you do it in this way?

3. If possible, could you please share a detailed proof of eqa.7? 

Thank you very much for your work!

**Comment by junleiz** [comment]
Especially why you multiple Hg with **negative** theta

**Comment by mohsaied** [comment]
I have the same question #2 up there.. it doesn't make a lot of sense to me. Why are inputs split into 2 parts anyways? I am guessing just because of GPU memory limits or something?

**Comment by alecwangcq** [comment]
Hi Mohsaied,

Yes, it's because the inputs take too much memory to fit in the GPU. (12GB)

**Comment by mohsaied** [comment]
thanks, and for the first question: why do you multiply by -theta?...

**Comment by mohsaied** [comment]
Also, I think that could mean there is a potential bug in your code when you do this in grasp.py
                `z += (grad_w[count].data * grad_f[count]).sum()`
If I am not mistaken, you should accumulate grad_f over the two input splits before multiplying by grad_w and accumulating into z.

**Comment by alecwangcq** [comment]
1. Eq (7) measures the importance of each weight. Removing one weight can be cast as setting its value to zero (i.e., add a perturbation -theta). So, that's why we need to multiply -theta. More details can be found in page 5.

2. These two for-loops #L76 and #L117 are used for computing the Hessian-vector product Hg. grad_w is the averaged gradient of the entire data, which is g.  H=\frac{1}{n} (H_1 + H_2, ..., H_n) is the Hessian over the entire data. So, what I am doing here is that: I first compute H_1 g, then H_2 g, and finally H_n g.  Does this make sense?

If you have any further question, please let me know.

**Comment by mohsaied** [comment]
Thanks for your reply, regarding the first point I think there is still something I am missing. Even in your re-derivation of the snip criteria, you specify it as follows: `theta_q * dL/d theta_q` , that is, you multiply the weight magnitude and take the derivative of the loss w.r.t. the weight.
However, in the snip paper, they introduce binary c variables per weight and their criteria is explicitly `dL/dc` i.e. without multiplying by theta_q and the derivative is taken w.r.t. c not theta_q. This is also what happens in the[ snip code](https://github.com/namhoonlee/snip-public/blob/f0284968bfa9b17d335587183b1c84cf628efe84/snip/model.py#L67).

I do not understand why those differences exist, to me these are two different pruning criteria. And tbh, I still don't understand why you multiply by theta_q in your criteria either. In the paper, the pruning importance is derived to be Hg, then there is a sentence that simply reads:

`GraSP uses eqn. (7) as the measure of the importance of each weight.` where eqn (7) is Hg. Then afterwards theta_q is multiplied to it for no apparent reason. If Hg quantifies the importance of the weight, why don't I just rank weights based on that **importance** and remove the least important ones?

Thank you for bearing with me on this one.

**Comment by alecwangcq** [comment]
Thanks for the questions.

- If you take derivative w.r.t. c, then you will get `\theta_q * dL/d \theta_q`, and in SNIP, they take the absolute value of it as the importance measure. In our paper, we interpret it from another perspective. That is, if we aim to preserve the original loss, then we will get the same pruning criteria as SNIP.

- eqn. (7) is `\delta Hg`, not only `Hg`. For pruning a single weight, `\delta` is simply -\theta_q. That's why we get eqn. (8).

**Comment by mohsaied** [comment]
Thanks Alec. I have another minor question: In your paper you state that:
`For a given pruning ratio p, we obtain the resulting pruning mask by computing the importance score of every weight, and removing the bottom p fraction of the weights`

but in the code it seems you keep the parameters with the smallest importance:
`keep_masks[m] = ((g / norm_factor) <= acceptable_score).float()`

Is this simply because of the -ve sign in -theta.Hg (so importance is flipped) or is there something else I am missing?

edit

in the paper you also state that: 

`if S(δ) is negative, then removing the corresponding weights will reduce the gradient flow, while if it is positive, (removing it) will increase the gradient flow`

I guess that implies that we want to keep the bottom (1-p) fraction of weights - which would be aligned with your codebase.
